### ISSUE TITLE
Unload key command in TPM 2.0

### ISSUE THREAD

**Issue by khanhnt93** [intel/tpm2-tss#596]
I'm working on TPM and I have a trouble. If my key tree to much, I must load all parrent keys, but TPM simulator just support 9 key slots. I fond unload key funtion but there was no unload key function in specification tpm 2.0.
Is there any way to unload key in TPM 2.0?
Thank you!

**Comment by williamcroberts** [comment]
I think you want Tss2_Sys_EvictControl.

See section 28 on context management in:
https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf

**Comment by martinezjavier** [comment]
@khanhnt93 AFAIK @jiazhang0 wrote a tpm2_flushcontext tool that uses Tss2_Sys_FlushContext. It should be useful for what you want to achieve.
