### ISSUE TITLE
Add commit message format requirements

### ISSUE THREAD

**Issue by tstruk** [intel/tpm2-tss#597]
Add commit message format requirements to CONTRIBUTING.md.
Commit message should include: subject, short description paragraph, and author's Signed-of-by

**Comment by flihp** [comment]
I just added a section to the CONTRIBUTING.md file in the `tpm2-abrmd`: https://github.com/01org/tpm2-abrmd/pull/235/commits/8c7138f0cb163ac8efb33eee15c6b21c36fcfca6. I cheated a bit and referenced a write-up describing how to properly format a git commit message: https://chris.beams.io/posts/git-commit/

**Comment by martinezjavier** [comment]
@flihp I did some comments on your PR. I think it would be nice if all the tpm2 projects follow the same rules so there's some consistency across all related repositories.

**Comment by tstruk** [comment]
@flihp what about Signed-of-by tag?

**Comment by martinezjavier** [comment]
@tstruk I mentioned that too :smiley:

**Comment by tstruk** [comment]
@martinezjavier I see that now. I like the the-canonical-patch-format you proposed.

**Comment by flihp** [comment]
Any chance we can knock this loose? Any objections to me taking the CONTRIBUING.md from tpm2-abrmd and turning it into a PR for the tss repo?

**Comment by martinezjavier** [comment]
Sounds good to me. It would be good that also have the same in the tpm2-tools CONTRIBUTING file.
