### ISSUE TITLE
PolicySecret ERROR

### ISSUE THREAD

**Issue by YaHosoda** [intel/tpm2-tss#651]
I am developing a program using TSS1.0(Nov１．2016).
I encountered a problem with PolicySecret error 0x98e and need help.
My program uses tpmtest.cpp as a base of development.
The situation is as follows:

1 Create TPM Keys as follows:

EK
｜--------
｜       |
MK      AK
｜
SK

2 Execute PolicySecret twice using HMAC session. At first, it ends without error. Then it ends with 0x98e
For clarification, I print out the values of Virtual Handle and Real Handle.

The value of Virtual/Real Handles differ at 2nd excution of the command. (See 25/26 Below)
I understand that the resource manager assigns Virtual Handle and my program calculates HMAC using that handles. On the other hand, TPM may calculate HMAC using Real Handle. 
That is my hypothesis.
Any suggestion for usage of Session Handle?

Command     Virtual/Real Handle   Line of Code in Attachment

1. CreatePrimary(EK) real=80000000, virtual=80000000     8381
2. HierarchyChangeAuth1 8421
3. HierarchyChangeAuth2 8431
4. StartAuthSession(Policy) real=3000000, virtual=3000000  8480
5. PolicySecret(ENDORSEMENT) 8494
6. Create(MK)  8515
7. PolicySecret(ENDORSEMENT) 8529
8. Load(MK) real=80000001, virtual=80000001  8542
9. Evict(MK) 8552
10. Create(SK) 8590
11. Load(SK) real=80000001, virtual=80000002   8598
12. PolicySecret(ENDORSEMENT) 8609
13. Create(AK) 8635
14. PolicySecret(ENDORSEMENT)  8645
15. Load(AK) real=80000001, virtual=80000003  8655
16. FlushContext(POLICY) 8664
17. StartAuthSession(POLICY) real=3000000, virtual=3000000  8668
18. StartAuthSession(HMAC) real=2000001, virtual=2000001   8678
19. ComputeCommandHMAC(LoadExternal) real=80000000, virtual=80000004 3706
20. ComputeCommandHMAC(HMAC_Start) real=80000001, virtual=80000005   3706
21. PolicySecret(SK) 8711
22. FlushContext(HMAC) 8717
23. FlushContext(POLICY) 8724
24. CertifyCreation(SK) 8738
25. StartAuthSession(POLICY) real=3000000, virtual=3000001 8745
26. StartAuthSession(HMAC) real=2000001, virtual=2000000  8754
27. ComputeCommandHMAC(LoadExternal) real=80000000, virtual=80000005   8782
28. ComputeCommandHMAC(HMAC_Start) real=80000001, virtual=80000004   8782
29. PolicySecret(SK) 8789

[tpmtest.cpp_0x98e_2.txt](https://github.com/intel/tpm2-tss/files/1516612/tpmtest.cpp_0x98e_2.txt)

**Comment by flihp** [comment]
Questions like this are usually better asked on the tpm2@01.org mailing list. The github issue tracker is more effective when used for specific / targeted questions. This seems to be more of a general support question.
