### ISSUE TITLE
ERROR WHILE COMPILING

### ISSUE THREAD

**Issue by yunusemreayhan** [intel/tpm2-tss#694]
sysapi_util/changeEndian.o
cc1: warnings being treated as errors
sysapi/sysapi_util/changeEndian.c: In function 'ChangeEndianQword':
sysapi/sysapi_util/changeEndian.c:33: error: integer constant is too large for 'long' type
sysapi/sysapi_util/changeEndian.c:33: error: integer constant is too large for 'long' type
sysapi/sysapi_util/changeEndian.c:33: error: integer constant is too large for 'long' type
sysapi/sysapi_util/changeEndian.c:33: error: integer constant is too large for 'long' type
make[3]: *** [sysapi/sysapi_util/changeEndian.lo] Error 1
make[2]: *** [/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/build/tpmtss-1.3.0/.stamp_built] Error 2
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/change/maxim-ic/lde-3.0/TREE/user/buildroot'
make: *** [rootfs-build] Error 2
make: Leaving directory `/home/change/maxim-ic/lde-3.0'
ldecmd build usip-0.2.3: *** ERROR 2, command failed: make -C /home/change/maxim-ic/lde-3.0 rootfs
/home/change/bin/ldecmd v1.0.2: *** ERROR 2, command failed: build rootfs
/home/change/maxim-ic/lde-3.0/user/buildroot

**Comment by martinezjavier** [comment]
@yunusemreayhan can you please share more details about your build environment (CPU architecture, compiler version, etc).

**Comment by yunusemreayhan** [comment]
this is fixed with addition of below patch 

/sysapi/sysapi_util/changeEndian.c

--- changeEndianOld.c	2017-12-14 14:51:39.310611858 +0300
+++ changeEndian.c	2017-12-14 14:52:24.350610420 +0300
@@ -30,14 +30,14 @@
 
 UINT64 ChangeEndianQword( UINT64 p )
 {
-    return( ((const UINT64)(((p)& 0xFF) << 56))    | \
-          ((const UINT64)(((p)& 0xFF00) << 40))   | \
-          ((const UINT64)(((p)& 0xFF0000) << 24)) | \
-          ((const UINT64)(((p)& 0xFF000000) << 8)) | \
-          ((const UINT64)(((p)& 0xFF00000000) >> 8)) | \
-          ((const UINT64)(((p)& 0xFF0000000000) >> 24)) | \
-          ((const UINT64)(((p)& 0xFF000000000000) >> 40)) | \
-          ((const UINT64)(((p)& 0xFF00000000000000) >> 56)) );
+    return( ((const UINT64)(((p)& 0xFFULL) << 56))    | \
+          ((const UINT64)(((p)& 0xFF00ULL) << 40))   | \
+          ((const UINT64)(((p)& 0xFF0000ULL) << 24)) | \
+          ((const UINT64)(((p)& 0xFF000000ULL) << 8)) | \
+          ((const UINT64)(((p)& 0xFF00000000ULL) >> 8)) | \
+          ((const UINT64)(((p)& 0xFF0000000000ULL) >> 24)) | \
+          ((const UINT64)(((p)& 0xFF000000000000ULL) >> 40)) | \
+          ((const UINT64)(((p)& 0xFF00000000000000ULL) >> 56)) );
 }
 
 UINT32 ChangeEndianDword( UINT32 p )

also similar error here fixed same

/sysapi/include/tcti_util.h

--- tcti_util_old.h	2017-12-14 14:58:27.374598751 +0300
+++ tcti_util.h	2017-12-14 14:58:44.662598204 +0300
@@ -46,7 +46,7 @@
 
 #include <tcti/common.h>
 
-#define TCTI_MAGIC   0x7e18e9defa8bc9e2
+#define TCTI_MAGIC   0x7e18e9defa8bc9e2ULL
 #define TCTI_VERSION 0x1
 
 #define TCTI_LOG_CALLBACK(ctx) ((TSS2_TCTI_CONTEXT_INTEL*)ctx)->logCallback

I fixed them myself, please add into code for next version.

**Comment by martinezjavier** [comment]
@yunusemreayhan it would be great if you can provide a pull request with your patch.

**Comment by yunusemreayhan** [comment]
Okay i will

**Comment by tstruk** [comment]
Closed with f6255dc
