### ISSUE TITLE
tag 1.3.0 unit test failed.

### ISSUE THREAD

**Issue by grandpaul** [intel/tpm2-tss#700]
Hi, 

I'm currently trying to package tpm2-tss 1.3.0 to Debian. But the unit test failed.
However, master works. Here are the logs on 1.3.0 tag of "make check"

PASS: test/unit/CheckOverflow
FAIL: test/unit/CommonPreparePrologue
FAIL: test/unit/CopyCommandHeader
PASS: test/unit/GetNumHandles
PASS: test/unit/marshal-TPM2B-simple
PASS: test/unit/marshal-UINT16
PASS: test/unit/marshal-UINT32
PASS: test/unit/tcti-device
PASS: test/unit/tcti-socket
PASS: test/unit/unmarshal-UINT16
PASS: test/unit/unmarshal-UINT32
============================================================================
Testsuite summary for tpm2-tss 1.3.0
============================================================================
# TOTAL: 11
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
============================================================================
Makefile:4784: recipe for target 'test-suite.log' failed
make[2]: *** [test-suite.log] Error 1
make[2]: Leaving directory '/tmp/d2/tpm2-tss/u1/tpm2-tss'
Makefile:4890: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 2
make[1]: Leaving directory '/tmp/d2/tpm2-tss/u1/tpm2-tss'
Makefile:5166: recipe for target 'check-am' failed
make: *** [check-am] Error 2

Attached is the test-suite.log
[test-suite.log](https://github.com/intel/tpm2-tss/files/1590898/test-suite.log)

**Comment by williamcroberts** [comment]
The linker is complaining about a PLT reloc type of 0x00 which is bad.

I don’t think this is anything in our codebase, but rather a bug in your build host.

Is this bug affecting you perhaps:
https://bugs.launchpad.net/ubuntu/+source/eglibc/+bug/773127

Bill

---------

**Comment by grandpaul** [comment]
No. I mean it works on master branch. So that means there must be something wrong on tag 1.3.0.

I tried to git diff 1.3.0 master. And just found the reason. Please see the attached patch that fix this problem. 
I'm not sure if I'm doing the right thing but it fixes the unit tests and all the test passed now.

```
Description: Fix failed unit tests
 There are some unknown reasons that make some of the unit tests failed.
 The failed cases are CommonPreparePrologue, CopyCommandHeader.
 The master branch from the upstream has already fixed the problem.
 This patch extracts the fixes from the upstream.
Forwarded: https://github.com/intel/tpm2-tss/issues/700
Author: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>
Last-Update: 2017-12-29
Index: tpm2-tss-1.3.0/Makefile.am
===================================================================
--- tpm2-tss-1.3.0.orig/Makefile.am
+++ tpm2-tss-1.3.0/Makefile.am
@@ -125,7 +125,7 @@ test_unit_tcti_socket_SOURCES = tcti/pla
 
 test_unit_CommonPreparePrologue_CFLAGS = $(CMOCKA_CFLAGS) $(AM_CFLAGS)
 test_unit_CommonPreparePrologue_LDFLAGS = -Wl,--unresolved-symbols=ignore-all
-test_unit_CommonPreparePrologue_LDADD = $(CMOCKA_LIBS)
+test_unit_CommonPreparePrologue_LDADD = $(CMOCKA_LIBS) $(libsapi)
 test_unit_CommonPreparePrologue_SOURCES = \
     test/unit/CommonPreparePrologue.c sysapi/sysapi_util/CommandUtil.c \
     sysapi/sysapi/ContextManagement.c
@@ -136,7 +136,7 @@ test_unit_GetNumHandles_SOURCES = test/u
 
 test_unit_CopyCommandHeader_CFLAGS = $(CMOCKA_CFLAGS) $(AM_CFLAGS)
 test_unit_CopyCommandHeader_LDFLAGS = -Wl,--unresolved-symbols=ignore-all
-test_unit_CopyCommandHeader_LDADD = $(CMOCKA_LIBS)
+test_unit_CopyCommandHeader_LDADD = $(CMOCKA_LIBS) $(libsapi)
 test_unit_CopyCommandHeader_SOURCES = \
     test/unit/CopyCommandHeader.c sysapi/sysapi_util/CommandUtil.c \
     sysapi/sysapi/ContextManagement.c sysapi/sysapi_util/changeEndian.c
```

**Comment by flihp** [comment]
PR is up with the fix

**Comment by flihp** [comment]
merged in https://github.com/intel/tpm2-tss/pull/715

**Comment by flihp** [comment]
to keep me from forgetting I'm going to close this now that we have the proposed fix in place. If you can test this @grandpaul and continue to see the same issue please re-open this and we'll triage again.
