### ISSUE TITLE
How do I load the OpenSSL private key into the TPM2?

### ISSUE THREAD

**Issue by searchmawnag** [intel/tpm2-tss#727]
I wanted load the OpenSSL private key into the TPM2 Device.

I found the source to change to structure of TPM2B_PRIVATE using the IBMTSS based OpenSSL private key.
 -> https://github.com/manoj23/pemtpm

How do I change the OpenSSL private key to the structure of TPM2B_PRIVATE based on INTELTSS?

Thank you.

**Comment by flihp** [comment]
Just for some context: this is probably better asked over @ https://github.com/tpm2-software/tpm2-tools. If we have or are going to develop tools for transforming certificates like this it'll happen there. Also @dguerri gave a talk @ fosdem last year that may be related: https://archive.fosdem.org/2017/schedule/event/tpm2/

**Comment by martinezjavier** [comment]
@searchmawnag I also know that @mgerstner also did a lot of work so the tpm2 tools could have better PEM/DER support. But I can't recall the details now...

**Comment by mgerstner** [comment]
Hi @searchmawnag,

`tpm2_readpublic` can write in OpenSSL PEM/DER format. `tpm2_sign` and `tpm2_quote` can output plain signatures that can be verified using OpenSSL. This is all focused on public keys and signature verification.

What exactly is your use case of importing an OpenSSL private key into the TPM? Typically you can have sealed or wrapped keys that are encrypted on disk and can only be loaded into the TPM in certain states.

It looks like TPM2_Import does also allow to import an unencrypted private key in some circumstances. But this would pretty much defeat the purpose of the TPM chip that the cleartext private key never leaves the TPM hardware.
